// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// InterfaceRequestMock is an autogenerated mock type for the InterfaceRequest type
type InterfaceRequestMock struct {
	mock.Mock
}

// CreateNewRequest provides a mock function with given fields: method, url, token, body, query
func (_m *InterfaceRequestMock) CreateNewRequest(method string, url string, token string, body io.Reader, query map[string]interface{}) ([]byte, int, error) {
	ret := _m.Called(method, url, token, body, query)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, string, io.Reader, map[string]interface{}) []byte); ok {
		r0 = rf(method, url, token, body, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, string, string, io.Reader, map[string]interface{}) int); ok {
		r1 = rf(method, url, token, body, query)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, string, io.Reader, map[string]interface{}) error); ok {
		r2 = rf(method, url, token, body, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
